[rule]
author = ["KZW"]
description = """ The alert look for .zip files being created in a file path containing windowns\\Temp """
from = "now-10m" 
name = "Data archive for potential exfiltration"
risk_score = 25
severity = "low"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000002"

query = '''
event.dataset:"endpoint.events.file" and event.action:(creation or overwrite) and file.name:*.zip and file.path:*Windows\\Temp\\* and process.name:powershell.exe
'''

[rule.alert_suppression]
group_by = ["host.name"]
duration = {value = 5, unit = "m"}
missing_fields_strategy = "suppress"

[[rule.threat]] 
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1074"
name = "Data Staged"
reference = "https://attack.mitre.org/techniques/T1074/"

[[rule.threat.technique.subtechnique]]
id = "T1074.001"
name = "Local Data Staging"
reference = "https://attack.mitre.org/techniques/T1074/001/"

[rule.threat.tactic]
id = "TA0009"
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"
