# [metadata]
# creation_date = "2026/09/17"


[rule]
author = ["KZW"]
description = """ Download file from Internet and save it in an NTFS Alternate Data Stream """
from = "now-6m" 
name = "Suspicious download of file using certutil and saving it as ADS"
risk_score = 75
severity = "high"
type = "query"

rule_id = "00000000-0000-0000-0000-000000000013"

query = '''
event.dataset:"windows.sysmon_operational" AND process.name:certutil.exe AND
process.args : ("-urlcache" OR "-verifyctl") AND process.args:"-f"  AND process.args : *\:*\:*
'''

[rule.alert_suppression]
group_by = ["host.name"]
missing_fields_strategy = "suppress"

[[rule.threat]] 
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1564"
name = "Hide Artifacts"
reference = "https://attack.mitre.org/techniques/T1564/"

[[rule.threat.technique.subtechnique]]
id = "T1564.004"
name = "NTFS File Attributes"
reference = "https://attack.mitre.org/techniques/T1564/004/"

[rule.threat.tactic]
id = "TA0005"
name = "Stealth"
reference = "https://attack.mitre.org/tactics/TA0005/"
