name: Updating Detections

on:
  push:
    paths:
      '**.toml' 
  workflow_dispatch:


jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY}}


    steps:
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6

      - name: Run Update Script
        env:
          ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY}}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run:
          python develop/update_alert.py


