name: TOML/Mitre Validation

on:
  push:
    paths:
      - "**.toml"
  workflow_dispatch:


jobs:
  toml-validation:
    runs-on: ubuntu-latest


    steps:
      
      - uses: actions/checkout@v4

      - run: python develop/validation.py
          
      - run: python develop/mitre.py
